name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: legal-assistant
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker
      run: gcloud auth configure-docker

    - name: Build and Deploy to Cloud Run
      run: |
        # Build and submit container
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE_NAME

        # Deploy to Cloud Run
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}"