name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: nomads-laws
  SERVICE_NAME: nomads-laws
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        service_account: 'nomads-laws-sa@nomads-laws.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Configure Docker
      run: gcloud auth configure-docker
    
    - name: Build and Deploy
      run: |
        # Build using Cloud Build
        gcloud builds submit \
          --tag gcr.io/nomads-laws/nomads-laws \
          --project nomads-laws \
          --timeout=1800s

        # Deploy to Cloud Run
        gcloud run deploy nomads-laws \
          --image gcr.io/nomads-laws/nomads-laws \
          --platform managed \
          --region $REGION \
          --project nomads-laws \
          --allow-unauthenticated \
          --set-env-vars "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}"